### ISSUE TITLE
Fix ability to delete task in weekly view

### ISSUE THREAD

**Issue by klbaker** [cse110-w21-group7/cse110-SP21-group7#234] opened 2021-05-29 20:20 UTC
## Detailed Description
The weekly view provides an overview of daily logs for a pre-specified week. From the weekly view, the tasks inside of each of these entries should not be edit-able. Currently, we can reproduce editing tasks from the following process:

1. Navigate to `weekly.html` for a week with entries
2. For any entry, click on the finished/unfinished icon next to any task
3. The trash can icon should appear after checking/unchecking the finished icon

## Context

Our final iteration of the high-fidelity wireframes addressed that the weekly view should only be used for navigation purposes for past daily logs. This issue is created in order to ensure that this specification is met.
## Possible Implementation

`TaskItem.js` is a custom component that contains a method `render()` for attaching event handlers in the shadow DOM. In order to address this issue, we should check that the control flow from the flag`_itemEntry.editable` is working as intended.
## Your Environment

* Browser Name and version: Chrome Version 90.0.4430.212 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): macOS Catalina v10.15.6

**Comment by NoahT** [comment] 2021-06-03 19:59
Apologies, @yuzilyu already fixed this bug. Duplicate of #274

**Closed as completed by NoahT** 2021-06-03 19:59 UTC
Labels: bug, duplicate
